my_city/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from webpanels.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('panel/', include('webpanels.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path, re_path
from .view import DashBoardView, AllReportsView, SingleReportView

app_name = 'reports'

urlpatterns = [
    
]

webpanels/urls.py
from django.urls import path, re_path
from .views import DashBoardView, AllReportsView, SingleReportView, LoginView

app_name = 'webpanels'

urlpatterns = [
    path('', DashBoardView.as_view(), name='dashboard'),
    path('reports/<int:pk>/', SingleReportView.as_view(), name='report'),
    path('reports/', AllReportsView.as_view(), name='reports'),
]

reports/models.py
from django.contrib.gis.db.models import PointField
from django.db import models


class Report(models.Model):
	title = models.CharField(max_length = 150)
	text = models.TextField()
	# location_latlng = PointField() # for postgres
	location = models.JSONField(default=str)
	created_at = models.DateTimeField(auto_now_add=True)
	edited_at = models.DateTimeField(auto_now=True)
	

	def __str__(self):
		return f"{self.pk} - {self.title}"


class ReportImage(models.Model):
	img = models.ImageField(upload_to='report_images')
	report = models.ForeignKey(Report, on_delete=models.CASCADE)
	

webpanels/models.py
from django.db import models

# Create your models here.

reports/views.py
from .models import Report, ReportImage

webpanels/views.py
from django.views.generic import ListView, TemplateView, DetailView
from reports.models import Report, ReportImage


class DashBoardView(TemplateView):
    template_name = "dashboard_home.html"


class LoginView(TemplateView):
    template_name = "login.html"


class AllReportsView(ListView):
    model = Report
    template_name = "webpanels/report_list.html"

class SingleReportView(DetailView):
    model = Report
    template_name = "webpanels/report_detail.html"

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %} | Панель администрирования "Мой город"</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/dashboard_home.html
{% extends '_base.html' %}

{% block title %}
    Главная
{% endblock title %}

{% block content %}
<h2>Hello world</h2>
<h3>Table of all reports <a href="{% url 'webpanels:reports' %}">here</a></h3>
{% endblock content %}

templates/login.html
<h3>Вход</h3>

<form action="" method=""POST>
    <label for="username">Введите имя пользователя</label>
    <input type="text" name="username" id="username">
    <label for="password">Введите пароль</label>
    <input type="password" name="password" id="password">
    <button type="submit">Войти</button>
</form>

templates/webpanels/report_detail.html
{% extends '_base.html' %}

{% block title %}
    жалоба №{{object.pk}}
{% endblock title %}

{% block content %}
    <h2>Жалоба №{{object.pk}}|{{object.title}}</h2>
    <p>{{object.text}}</p>
    {% for picture in object.reportimage_set.all %}
        <img src="{{picture.img.url}}" alt="">
    {% empty %}
        <tr>No pictures</tr>
    {% endfor %}
    <a href="{% url 'webpanels:reports' %}">Назад</a>
{% endblock content %}

templates/webpanels/report_list.html
{% extends '_base.html' %}

{% block title %}
    Список жалоб
{% endblock title %}

{% block content %}
<h2>List of reports here</h2>
<table>
    <th>
        <td>ID</td>
        <td>Title</td>
        <td>Author</td>
        <td>Urgent</td>
    </th>
    {% for report in object_list %}
    <tr>
        <td>{{report.pk}}</td>
        <td><a href="{% url 'webpanels:report' pk=report.pk %}">Report {{report.pk}}</a></td>
        <td>User23432</td>
        <td>Not urgent</td>
    </tr>
    {% empty %}
        <tr>No reports found</tr>
    {% endfor %}

-->Pagination
{% endblock content %}